import streamlit as st
import requests
from fpdf import FPDF
import tempfile
import os

# ------------------- Config -------------------
st.set_page_config(page_title="AutoBio-X", layout="centered")

BASE_API = "https://autobio-x.onrender.com"

# ------------------- UI Header -------------------
st.image("logo.png", width=220)
st.title("🧬 AutoBio-X: Gene Explorer & Drug Matcher")

st.markdown("""
A real-time AI-powered tool to explore gene expression, mutation impact, and targeted drug matches in breast cancer.
""")

# ------------------- API Connectors -------------------

def get_expression_data(gene):
    try:
        r = requests.get(f"{BASE_API}/expression/{gene}")
        return r.json().get("expression", {})
    except:
        return {"error": "Failed to fetch expression data."}

def get_mutation_data(gene):
    try:
        r = requests.get(f"{BASE_API}/mutation/{gene}")
        return r.json()
    except:
        return [{"error": "Failed to fetch mutation data."}]

def get_drug_data(gene):
    try:
        r = requests.get(f"{BASE_API}/drugs/{gene}")
        return r.json()
    except:
        return [{"error": "Failed to fetch drug data."}]

# ------------------- Gene Input -------------------

gene = st.text_input("🔍 Enter Gene Symbol (e.g., TP53, BRCA1)").strip().upper()

if gene:
    # ------------------- Expression Section -------------------
    st.subheader("📊 Expression Data")
    expr = get_expression_data(gene)
    if "error" in expr:
        st.warning(expr["error"])
    else:
        st.json(expr)

    # ------------------- Mutation Section -------------------
    st.subheader("🧬 Mutation Info")
    muts = get_mutation_data(gene)
    if isinstance(muts, list) and "error" in muts[0]:
        st.warning(muts[0]["error"])
    else:
        st.json(muts)

    # ------------------- Drug Match Section -------------------
    st.subheader("💊 Drug Matches")
    drugs = get_drug_data(gene)
    if isinstance(drugs, list) and "error" in drugs[0]:
        st.warning(drugs[0]["error"])
    else:
        st.json(drugs)

    # ------------------- PDF Download -------------------
    # Clean non-latin characters for PDF (like emojis)
def safe_text(text):
    return str(text).encode('latin1', 'ignore').decode('latin1')

# ✅ Only show button if all data is present
if "error" not in expr and "error" not in muts[0] and "error" not in drugs[0]:
    if st.button("📥 Download Report as PDF"):
        pdf = FPDF()
        pdf.add_page()
        pdf.set_font("Arial", size=14)
        pdf.set_text_color(33, 33, 33)
        pdf.cell(200, 10, txt=safe_text(f"Gene Report: {gene}"), ln=True, align='C')
        pdf.ln(10)

        pdf.set_font("Arial", size=12)
        pdf.multi_cell(0, 10, txt=safe_text("Expression Data:\n" + str(expr)))
        pdf.ln(5)
        pdf.multi_cell(0, 10, txt=safe_text("Mutation Info:\n" + str(muts)))
        pdf.ln(5)
        pdf.multi_cell(0, 10, txt=safe_text("Drug Matches:\n" + str(drugs)))
        pdf.ln(10)

        pdf.set_font("Arial", style="I", size=10)
        pdf.set_text_color(100, 100, 100)
        pdf.cell(200, 10, txt=safe_text("Generated by Syeda Rehmat — Founder, BioZero"), ln=True, align='C')

        with tempfile.NamedTemporaryFile(delete=False, suffix=".pdf") as tmpfile:
            pdf.output(tmpfile.name)
            with open(tmpfile.name, "rb") as f:
                st.download_button(
                    label="⬇️ Download PDF Report",
                    data=f,
                    file_name=f"{gene}_AutoBioX_Report.pdf",
                    mime="application/pdf"
                )
            os.unlink(tmpfile.name)


             
# ------------------- Footer -------------------
st.markdown("""
<hr style='border: 1px solid #ddd;'>
<div style="text-align: center; color: gray;">
    Created by <b>Syeda Rehmat</b> — Founder, <i>BioZero</i>
</div>
""", unsafe_allow_html=True)
